# Generated by Django 5.0.6 on 2025-05-27 21:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0018_remove_city_country_remove_city_delivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_in_days', models.PositiveIntegerField()),
                ('addition_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', related_query_name='cities', to='profiles.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('none', 'Unassigned'), ('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='none')),
                ('license', models.ImageField(blank=True, null=True, upload_to='')),
                ('address', models.TextField(blank=True, default='', max_length=200)),
                ('remarks', models.TextField(blank=True, default='')),
                ('latest_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('profit_percentage', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('order_by_phone', models.BooleanField(default=False)),
                ('company', models.BooleanField(default=False)),
                ('key_person', models.CharField(blank=True, default='', max_length=255)),
                ('key_person_phone', models.CharField(blank=True, default='', max_length=255)),
                ('area_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles_area_manager', related_query_name='assigned_profiles_area_manager', to='accounts.areamanager')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', related_query_name='profiles', to='profiles.city')),
                ('data_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles_data_entry', related_query_name='assigned_profiles_data_entry', to='accounts.dataentry')),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles_delivery', related_query_name='assigned_profiles_delivery', to='accounts.delivery')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles_manager', related_query_name='assigned_profiles_manager', to='accounts.manager')),
                ('payment_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', related_query_name='profiles', to='profiles.paymentperiod')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_profiles_sales', related_query_name='assigned_profiles_sales', to='accounts.sales')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', related_query_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField(max_length=400)),
                ('mark_as_solved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaints', related_query_name='user_complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='profiles_co_user_id_ba5513_idx')],
            },
        ),
    ]
