version: '3.8'

services:
  web:
    build: .
    container_name: pharmasky_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - SECRET_KEY=pharmasky-change-this-to-a-very-long-random-secret-key-in-production-12345
      - ALLOWED_HOSTS=167.71.40.9,129.212.140.152,164.90.217.81,localhost,127.0.0.1
      - DATABASE_URL=postgresql://doadmin:AVNS_g62jyoo4mcu0BkfRsdM@pharmasky-db-do-user-17921548-0.h.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    env_file:
      - production.env
    depends_on:
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pharmasky_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - web
    networks:
      - pharmasky_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pharmasky_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pharmasky_network
    restart: unless-stopped

  celery:
    build: .
    container_name: pharmasky_celery
    command: celery -A project worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
    env_file:
      - production.env
    depends_on:
      - web
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: pharmasky_celery_beat
    command: celery -A project beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - production.env
    depends_on:
      - web
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  redis_data:

networks:
  pharmasky_network:
    driver: bridge
