services:
  web:
    build: .
    container_name: pharmasky_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DEBUG=False
      - DJANGO_SETTINGS_MODULE=project.settings_simple
      - SECRET_KEY=pharmasky-change-this-to-a-very-long-random-secret-key-in-production-12345
      - ALLOWED_HOSTS=167.71.40.9,129.212.140.152,164.90.217.81,localhost,127.0.0.1
      - DATABASE_URL=postgresql://doadmin:AVNS_g62jyoo4mcu0BkfRsdM@pharmasky-db-do-user-17921548-0.h.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      - CORS_ALLOWED_ORIGINS=http://167.71.40.9,http://129.212.140.152,http://164.90.217.81,http://localhost
      - CSRF_TRUSTED_ORIGINS=http://167.71.40.9,http://129.212.140.152,http://164.90.217.81,http://localhost
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    env_file:
      - production.env
    depends_on:
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: pharmasky_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./ssl:/etc/nginx/ssl
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - web
    networks:
      - pharmasky_network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pharmasky_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - pharmasky_network
    restart: unless-stopped

  celery:
    build: .
    container_name: pharmasky_celery
    command: celery -A project worker --loglevel=info
    volumes:
      - .:/app
      - media_volume:/app/media
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - production.env
    depends_on:
      - web
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

  celery-beat:
    build: .
    container_name: pharmasky_celery_beat
    command: celery -A project beat --loglevel=info --schedule=/app/celerybeat/celerybeat-schedule
    volumes:
      - .:/app
      - celerybeat_data:/app/celerybeat
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - production.env
    depends_on:
      - web
      - redis
    networks:
      - pharmasky_network
    restart: unless-stopped

  # AI Agent Services
  
  ollama:
    image: ollama/ollama:latest
    container_name: pharmasky_ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - pharmasky_network
    restart: unless-stopped
    # Running on CPU (no GPU required)
  
  fastapi_db:
    image: postgres:15-alpine
    container_name: pharmasky_fastapi_db
    environment:
      POSTGRES_DB: agent_db
      POSTGRES_USER: agent
      POSTGRES_PASSWORD: agent_password_change_in_production
    volumes:
      - fastapi_db_data:/var/lib/postgresql/data
    networks:
      - pharmasky_network
    restart: unless-stopped
  
  fastapi_agent:
    build: ./fastapi_agent
    container_name: pharmasky_fastapi_agent
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi_agent:/app
      - audio_storage:/app/recordings
      - rag_data:/app/rag_data
      - ./rag_data:/app/shared_rag_data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - DEBUG=True
      - DJANGO_API_URL=http://web:8000
      - DJANGO_API_KEY=${AI_AGENT_API_KEY:-change-this-in-production}
      - OLLAMA_URL=http://ollama:11434
      - OLLAMA_MODEL=phi3:mini
      - DATABASE_URL=postgresql://agent:agent_password_change_in_production@fastapi_db:5432/agent_db
      - CHROMA_PERSIST_DIR=/app/chroma_db
      - WHISPER_MODEL=base
      - TTS_LANGUAGE=ar
      - AUDIO_STORAGE_PATH=/app/recordings
    depends_on:
      - ollama
      - fastapi_db
      - web
    networks:
      - pharmasky_network
    restart: unless-stopped

volumes:
  static_volume:
  media_volume:
  redis_data:
  celerybeat_data:
  ollama_data:
  fastapi_db_data:
  audio_storage:
  rag_data:

networks:
  pharmasky_network:
    driver: bridge
