# Generated by Django 5.0.6 on 2025-05-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0049_productcode_remove_advertising_content_type_and_more'),
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_invoice_number', models.CharField(blank=True, default='', max_length=255)),
                ('items_count', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('locked', 'Locked'), ('closed', 'Closed')], default='placed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_invoices', related_query_name='purchase_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('received', 'Received'), ('not_received', 'Not Received')], default='placed')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='invoices.purchaseinvoice')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_items', related_query_name='purchase_invoice_items', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_items', related_query_name='purchase_invoice_items', to='market.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('closed', 'Closed')], default='placed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_return_invoices', related_query_name='purchase_return_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='invoices.purchasereturninvoice')),
                ('purchase_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_return_invoice_items', related_query_name='purchase_return_invoice_items', to='invoices.purchaseinvoiceitem')),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('closed', 'Closed')], default='placed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sold_invoices', related_query_name='sold_invoices', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_invoices', related_query_name='sale_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleInvoiceDeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('received', 'Received'), ('not_received', 'Not Received')], default='placed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', related_query_name='deleted_items', to='invoices.saleinvoice')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoice_deleted_items', related_query_name='sale_invoice_deleted_items', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoice_deleted_items', related_query_name='sale_invoice_deleted_items', to='market.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('received', 'Received'), ('not_received', 'Not Received')], default='placed')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='invoices.saleinvoice')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_invoice_items', related_query_name='sale_invoice_items', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_invoice_items', related_query_name='sale_invoice_items', to='market.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='sale_invoice_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_item', related_query_name='purchase_invoice_item', to='invoices.saleinvoiceitem'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceDeletedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('received', 'Received'), ('not_received', 'Not Received')], default='placed')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_items', related_query_name='deleted_items', to='invoices.purchaseinvoice')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_deleted_items', related_query_name='purchase_invoice_deleted_items', to='offers.offer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_deleted_items', related_query_name='purchase_invoice_deleted_items', to='market.product')),
                ('sale_invoice_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_deleted_items', related_query_name='purchase_invoice_deleted_items', to='invoices.saleinvoiceitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleReturnInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('placed', 'Placed'), ('closed', 'Closed')], default='placed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_return_invoices', related_query_name='sale_return_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaleReturnInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='invoices.salereturninvoice')),
                ('sale_invoice_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_return_invoice_items', related_query_name='sale_return_invoice_items', to='invoices.saleinvoiceitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['seller'], name='invoices_sa_seller__d3c692_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['user'], name='invoices_sa_user_id_41c6fe_idx'),
        ),
        migrations.AddIndex(
            model_name='saleinvoice',
            index=models.Index(fields=['user', 'seller'], name='invoices_sa_user_id_b0c871_idx'),
        ),
    ]
