# Generated by Django 5.0.6 on 2025-05-27 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('credit_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('remaining_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', related_query_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ib', 'Initial balance'), ('pi', 'Purchase Invoice'), ('si', 'Sale Invoice'), ('pr', 'Purchase Return'), ('sr', 'Sale Return'), ('pp', 'Purchase Payment'), ('sp', 'Sale Payment'), ('f', 'Refund')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transactions', to='finance.account')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_transactions', related_query_name='account_transactions', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='PurchasePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ip', 'Instapay'), ('c', 'Cash'), ('w', 'Wallet'), ('p', 'Products')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_payments', related_query_name='purchase_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='SalePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('ip', 'Instapay'), ('c', 'Cash'), ('w', 'Wallet'), ('p', 'Products')])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('at', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_payments', related_query_name='sale_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user'], name='finance_acc_user_id_cfffa6_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['account'], name='finance_acc_account_2829da_idx'),
        ),
        migrations.AddIndex(
            model_name='accounttransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='finance_acc_content_7c10e2_idx'),
        ),
        migrations.AddIndex(
            model_name='purchasepayment',
            index=models.Index(fields=['user'], name='finance_pur_user_id_771585_idx'),
        ),
        migrations.AddIndex(
            model_name='salepayment',
            index=models.Index(fields=['user'], name='finance_sal_user_id_061c9d_idx'),
        ),
    ]
