# Generated by Django 5.0.6 on 2025-06-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasepayment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='remarks',
            field=models.TextField(blank=True, default=''),
        ),
    ]
