# Generated by Django 5.0.6 on 2025-06-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_purchasepayment_remarks_salepayment_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('d', 'Deposit'), ('w', 'Withdrawal')])),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='finance_saf_type_cffc68_idx')],
            },
        ),
    ]
