# Generated by Django 5.0.6 on 2025-05-09 00:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('redirect_type', models.CharField(choices=[('i', 'Internal'), ('e', 'External')], default='i')),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, default='')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertisment', related_query_name='advertisment', to='contenttypes.contenttype')),
            ],
        ),
    ]
