# Generated by Django 5.0.6 on 2024-07-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_later', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accounts.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.FloatField(default=0)),
                ('offer_price', models.FloatField(default=0.0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items', to='market.cart_store')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='market.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_token', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order', to='market.cart_store')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.manager')),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_ph', to='accounts.pharmacy')),
                ('pharmacyprofile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_phpro', to='accounts.pharmacyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_token', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='market.order_store')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.cart_store')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.manager')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='market.order_store')),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_ph', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.offer')),
            ],
        ),
        migrations.CreateModel(
            name='Our_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_later', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('manager', models.ManyToManyField(related_name='manager_cart', to='accounts.manager')),
                ('store', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='our_cart', to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('e_name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('public_price', models.FloatField(default=0.0)),
                ('effective_material', models.CharField(default='المادة الفعالة', max_length=100)),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], max_length=20)),
                ('shape', models.CharField(choices=[('افلام', 'افلام'), ('اقراص', 'اقراص'), ('اكياس', 'اكياس'), ('امبولات', 'امبولات'), ('اسبراي', 'اسبراي'), ('اسبراي الانف', 'اسبراي الانف'), ('اسبراي الفم', 'اسبراي الفم'), ('اقراص استحلاب', 'اقراص استحلاب'), ('اقماع شرجية', 'اقماع شرجية'), ('اقماع مهبلية', 'اقماع مهبلية'), ('المحلول', 'المحلول'), ('برطمان', 'برطمان'), ('بلسم', 'بلسم'), ('بودرة', 'بودرة'), ('بودرة استنشاق', 'بودرة استنشاق'), ('جل', 'جل'), ('جل للعين', 'جل للعين'), ('جل مهبلي', 'جل مهبلي'), ('حبيبات فوارة', 'حبيبات فوارة'), ('حقنة معباة', 'حقنة معباه'), ('حليب مجفف', 'حليب مجفف'), ('خرطوشة', 'خرطوشة'), ('رغوة', 'رغوة'), ('زيت', 'زيت'), ('سائل', 'سائل'), ('شامبو', 'شامبو'), ('شراب', 'شراب'), ('صابون', 'صابون'), ('غسول للفم', 'غسول للفم'), ('غسول مهبلي', 'غسول مهبلي'), ('فيال', 'فيال'), ('قطرة انف', 'قطرة انف'), ('قطرة الاذن', 'قطرة الاذن'), ('قطرة للعين', 'قطرة للعين'), ('قطعة', 'قطعة'), ('قلم معبأ', 'قلم معبأ'), ('كبسولات', 'كبسولات'), ('كريم', 'كريم'), ('كريم مهبلي', 'كريم مهبلي'), ('لاصقات', 'لاصقات'), ('لوشن', 'لوشن'), ('لولب', 'لولب'), ('محلول استنشاق', 'محلول استنشاق'), ('محلول شرجي', 'محلول شرجي'), ('محلول وريدي', 'محلول وريدي'), ('مرهم', 'مرهم'), ('مرهم شرجي', 'مرهم شرجي'), ('مرهم للعين', 'مرهم للعين'), ('مستحلب', 'مستحلب'), ('معجون اسنان', 'معجون اسنان'), ('معلق', 'معلق'), ('نقط فم', 'نقط فم')], max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.company')),
            ],
        ),
        migrations.CreateModel(
            name='OfferCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.FloatField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offercompany', to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='Offer_Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.FloatField(default=0)),
                ('amount', models.IntegerField(default=1)),
                ('expire_date', models.DateField()),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offerspharmacy', to='market.product')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='market.product'),
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='Related_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternatives', models.ManyToManyField(blank=True, related_name='alternatives', to='market.product')),
                ('instances', models.ManyToManyField(related_name='instances', to='market.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_product', to='market.product')),
            ],
        ),
    ]
