# Generated by Django 5.0.6 on 2024-07-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_product_shape_order_sales_sales_cart_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='e_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='effective_material',
            field=models.CharField(default='المادة الفعالة', max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
