# Generated by Django 5.0.6 on 2024-08-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0003_alter_product_e_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coding_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store')),
            ],
        ),
    ]
