# Generated by Django 5.0.6 on 2024-08-03 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_coding_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='market.coding_item'),
            preserve_default=False,
        ),
    ]
