# Generated by Django 5.0.6 on 2024-08-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('market', '0005_offer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_store',
            name='pharmacyprofile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_phprof', to='accounts.pharmacyprofile'),
        ),
        migrations.CreateModel(
            name='Cart_Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_ph', to='accounts.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='CartItems_Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='items_ph', to='market.cart_ph')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartitems_ph', to='market.offer_pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('is_token', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_fph', to='market.cart_ph')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_manager', to='accounts.manager')),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_phpro', to='accounts.pharmacy')),
                ('pharmacyprofile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_phpro', to='accounts.pharmacyprofile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItems_ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('is_accept', models.BooleanField(default=False)),
                ('is_received', models.BooleanField(default=False)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.cart_ph')),
                ('manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_resell', to='accounts.manager')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_fph', to='market.order_ph')),
                ('pharmacy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderitems_phpro', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.offer_pharmacy')),
            ],
        ),
    ]
