# Generated by Django 5.0.6 on 2024-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_maxoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
