# Generated by Django 5.0.6 on 2024-08-15 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_alter_offer_offer_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maxoffer',
            name='offer_price',
        ),
        migrations.RemoveField(
            model_name='maxoffer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='maxoffer',
            name='store',
        ),
        migrations.AddField(
            model_name='maxoffer',
            name='offer',
            field=models.ForeignKey(default=577, on_delete=django.db.models.deletion.CASCADE, to='market.offer'),
            preserve_default=False,
        ),
    ]
