# Generated by Django 5.0.6 on 2024-08-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_remove_maxoffer_offer_price_remove_maxoffer_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_pharmacy',
            name='offer_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='OfferCompany',
        ),
    ]
