# Generated by Django 5.0.6 on 2024-08-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_offer_pharmacy_offer_price_delete_offercompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='min_purchase',
            field=models.FloatField(default=0),
        ),
    ]
