# Generated by Django 5.0.6 on 2024-08-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_offer_min_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaxOffer',
        ),
    ]
