# Generated by Django 5.0.6 on 2024-08-20 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_delete_maxoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.FloatField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.offer')),
            ],
        ),
    ]
