# Generated by Django 5.0.6 on 2024-09-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_maxoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_sales',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order_sales',
            name='pharmacyprofile',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='manager',
        ),
        migrations.AddField(
            model_name='product',
            name='needed',
            field=models.BooleanField(default=False),
        ),
    ]
