# Generated by Django 5.0.6 on 2024-09-03 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_ads_remove_order_sales_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='needed',
        ),
    ]
