# Generated by Django 5.0.6 on 2024-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_remove_product_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='needed',
            field=models.BooleanField(default=False),
        ),
    ]
