# Generated by Django 5.0.6 on 2024-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0017_product_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='e_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='e_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
