# Generated by Django 5.0.6 on 2024-09-16 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_e_name'),
        ('market', '0018_category_e_name_company_e_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('period_in_days', models.PositiveIntegerField()),
                ('addition_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='is_max',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='letter',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='PharmacyCreditLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_credit_limit', related_query_name='pharmacy_credit_limit', to='accounts.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_received', models.BooleanField(default=False)),
                ('received_date', models.DateTimeField(blank=True, editable=False, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_invoices', related_query_name='ph_invoices', to='accounts.pharmacy')),
                ('sales', models.ForeignKey(limit_choices_to=models.Q(('role', 'MANAGER'), ('role', 'SALES'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', related_query_name='sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cd', 'Cash Day'), ('cc', 'Cash Car'), ('pp', 'Post Paid')], max_length=2)),
                ('payment_on', models.DateField(blank=True, null=True)),
                ('payment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('addition_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('total_payment_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('paid_on', models.DateField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', related_query_name='payments', to='market.paymentperiod')),
                ('pharmacy_invoice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payments', to='market.pharmacyinvoice')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('min_purchase', models.FloatField(blank=True, default=0)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', related_query_name='invoice_details', to='market.coding_item')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', related_query_name='invoice_details', to='market.offer')),
                ('pharmacy_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', related_query_name='invoice_details', to='market.pharmacyinvoice')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', related_query_name='invoice_details', to='market.product')),
                ('store', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', related_query_name='invoice_details', to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyPaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_periods', models.ManyToManyField(related_name='pharmacy_payment_periods', related_query_name='pharmacy_payment_periods', to='market.paymentperiod')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_payment_period', related_query_name='pharmacy_payment_period', to='accounts.pharmacy')),
            ],
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
