# Generated by Django 5.0.6 on 2024-09-19 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_paymentperiod_offer_is_max_alter_product_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pharmacy_invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', related_query_name='payment', to='market.pharmacyinvoice'),
        ),
    ]
