# Generated by Django 5.0.6 on 2024-09-28 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_storeprofile_data_entry_and_more'),
        ('market', '0020_pharmacyinvoicedetail_is_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyinvoicedetail',
            name='is_accepted',
        ),
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='c', to='market.coding_item'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='market.coding_item'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='market.offer'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='pharmacy_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='market.pharmacyinvoice'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='market.product'),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='store',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='accounts.store'),
        ),
        migrations.CreateModel(
            name='StoreInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_invoices', related_query_name='store_invoices', to='accounts.store')),
            ],
        ),
        migrations.RenameModel(
            old_name='Coding_Item',
            new_name='StoreProductCode',
        ),
        migrations.CreateModel(
            name='StoreInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('quantity', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_details', related_query_name='store_invoice_details', to='market.storeproductcode')),
                ('pharmacy_invoice_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store_invoice_detail', related_query_name='store_invoice_detail', to='market.pharmacyinvoicedetail')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_details', related_query_name='store_invoice_details', to='market.product')),
                ('store_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_invoice_details', related_query_name='store_invoice_details', to='market.storeinvoice')),
            ],
        ),
    ]
