# Generated by Django 5.0.6 on 2024-09-28 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0021_remove_pharmacyinvoicedetail_is_accepted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeproductcode',
            old_name='item',
            new_name='product',
        ),
    ]
