# Generated by Django 5.0.6 on 2024-10-05 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0022_rename_item_storeproductcode_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='original_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='original_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storeinvoicedetail',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoice',
            name='sales',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('role', 'MANAGER'), ('role', 'SALES'), _connector='OR'), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_invoices', related_query_name='sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MaxOffer',
        ),
    ]
