# Generated by Django 5.0.6 on 2024-10-10 00:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_areamanager_rename_user_pharmacyprofile_pharmacy_and_more'),
        ('market', '0023_offer_original_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ads',
            new_name='Advertising',
        ),
        migrations.RemoveField(
            model_name='order_ph',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems_ph',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitems_ph',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cart_store',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='order_store',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems_store',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems_ph',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitems_sales',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitems_sales',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cartitems_store',
            name='item',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='notify',
            name='product',
        ),
        migrations.RemoveField(
            model_name='offer_pharmacy',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='offer_pharmacy',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems_ph',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order_ph',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order_ph',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='order_ph',
            name='pharmacyprofile',
        ),
        migrations.RemoveField(
            model_name='orderitems_ph',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_sales',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order_sales',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='order_sales',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_store',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='order_store',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='order_store',
            name='pharmacyprofile',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems_ph',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='orderitems_ph',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitems_sales',
            name='sales',
        ),
        migrations.RemoveField(
            model_name='our_cart',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='our_cart',
            name='store',
        ),
        migrations.RemoveField(
            model_name='related_products',
            name='alternatives',
        ),
        migrations.RemoveField(
            model_name='related_products',
            name='instances',
        ),
        migrations.RemoveField(
            model_name='related_products',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sales_cart',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='sales_cart',
            name='sales',
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='alternatives',
            field=models.ManyToManyField(blank=True, to='market.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='instances',
            field=models.ManyToManyField(blank=True, to='market.product'),
        ),
        migrations.AddField(
            model_name='storeinvoicedetail',
            name='is_recieved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PharmacyInvoiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('r', 'Recieved from store'), ('s', 'Shipped'), ('d', 'Delivered'), ('p', 'Paid')], max_length=1)),
                ('checked', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('icon_class', models.CharField(choices=[('a', 'pi-thumbs-up'), ('r', 'pi-box'), ('s', 'pi-truck'), ('d', 'pi-check'), ('p', 'pi-money-bill')], max_length=1)),
                ('style_class', models.CharField(choices=[('a', 'bg-primary'), ('r', 'bg-primary'), ('s', 'bg-primary'), ('d', 'bg-primary'), ('p', 'bg-primary')], max_length=1)),
                ('pharmacy_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_statuses', related_query_name='pharmacy_invoice_statuses', to='market.pharmacyinvoice')),
            ],
            options={
                'verbose_name_plural': 'Pharmacy invoice statuses',
            },
        ),
        migrations.CreateModel(
            name='PharmacyOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_precentage', models.FloatField(default=0)),
                ('amount', models.IntegerField(default=1)),
                ('expire_date', models.DateField()),
                ('offer_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_offers', related_query_name='pharmacy_offers', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_offers', related_query_name='pharmacy_offers', to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='PharmcyProductWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product')),
            ],
            options={
                'unique_together': {('product', 'pharmacy')},
            },
        ),
        migrations.DeleteModel(
            name='Cart_Ph',
        ),
        migrations.DeleteModel(
            name='Cart_Store',
        ),
        migrations.DeleteModel(
            name='CartItems_Ph',
        ),
        migrations.DeleteModel(
            name='CartItems_Sales',
        ),
        migrations.DeleteModel(
            name='CartItems_Store',
        ),
        migrations.DeleteModel(
            name='Notify',
        ),
        migrations.DeleteModel(
            name='Offer_Pharmacy',
        ),
        migrations.DeleteModel(
            name='Order_Ph',
        ),
        migrations.DeleteModel(
            name='Order_Sales',
        ),
        migrations.DeleteModel(
            name='Order_Store',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='OrderItems_ph',
        ),
        migrations.DeleteModel(
            name='OrderItems_Sales',
        ),
        migrations.DeleteModel(
            name='Our_cart',
        ),
        migrations.DeleteModel(
            name='Related_Products',
        ),
        migrations.DeleteModel(
            name='Sales_Cart',
        ),
    ]
