# Generated by Django 5.0.6 on 2024-10-12 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0024_rename_ads_advertising_remove_order_ph_cart_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'e_name'], name='market_product_name_idx'),
        ),
    ]
