# Generated by Django 5.0.6 on 2024-10-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0025_alter_category_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_illegal',
            field=models.BooleanField(default=False),
        ),
    ]
