# Generated by Django 5.0.6 on 2024-10-13 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_complaint_remove_complaints_office_pharmacy_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0026_product_is_illegal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer',
            new_name='StoreOffer',
        ),
        migrations.RemoveField(
            model_name='pharmacyinvoicedetail',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='pharmacyinvoicedetail',
            name='store',
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='offer_content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('app_label__in', ['market']), ('model__in', ['pharmacyoffer', 'storeoffer'])), on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='offer_object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='seller_content_type',
            field=models.ForeignKey(default=1, limit_choices_to=models.Q(('app_label__in', ['accounts']), ('model__in', ['pharmacy', 'store'])), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='seller_object_id',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyoffer',
            name='original_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='pharmacyoffer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicedetail',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_invoice_details', related_query_name='pharmacy_invoice_details', to='market.storeproductcode'),
        ),
    ]
