# Generated by Django 5.0.6 on 2024-10-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0027_rename_offer_storeoffer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoffer',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pharmacyoffer',
            name='amount',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
