# Generated by Django 5.0.6 on 2024-10-14 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0028_pharmacyoffer_remaining_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeinvoicedetail',
            name='store_invoice',
        ),
        migrations.RemoveField(
            model_name='storeinvoicedetail',
            name='code',
        ),
        migrations.RemoveField(
            model_name='storeinvoicedetail',
            name='pharmacy_invoice_detail',
        ),
        migrations.RemoveField(
            model_name='storeinvoicedetail',
            name='product',
        ),
        migrations.CreateModel(
            name='SellerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_object_id', models.PositiveBigIntegerField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('seller_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoices', related_query_name='seller_invoices', to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='SellerInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('offer_discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_recieved', models.BooleanField(default=False)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('code', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice_details', related_query_name='seller_invoice_details', to='market.storeproductcode')),
                ('pharmacy_invoice_detail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_invoice_detail', related_query_name='seller_invoice_detail', to='market.pharmacyinvoicedetail')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice_details', related_query_name='seller_invoice_details', to='market.product')),
                ('seller_invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice_details', related_query_name='seller_invoice_details', to='market.sellerinvoice')),
            ],
        ),
        migrations.DeleteModel(
            name='StoreInvoice',
        ),
        migrations.DeleteModel(
            name='StoreInvoiceDetail',
        ),
    ]
