# Generated by Django 5.0.6 on 2024-10-14 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0029_remove_storeinvoicedetail_store_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinvoicedetail',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoice_details', related_query_name='seller_invoice_details', to='market.storeproductcode'),
        ),
    ]
