# Generated by Django 5.0.6 on 2024-10-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0030_alter_sellerinvoicedetail_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyoffer',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
