# Generated by Django 5.0.6 on 2024-10-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0031_alter_pharmacyoffer_discount_precentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoffer',
            name='is_max',
            field=models.BooleanField(default=False),
        ),
    ]
