# Generated by Django 5.0.6 on 2024-10-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0032_pharmacyoffer_is_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pharmacyoffer',
            old_name='expire_date',
            new_name='product_expiry_date',
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='product_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='product_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
