# Generated by Django 5.0.6 on 2024-10-15 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0033_rename_expire_date_pharmacyoffer_product_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='public_price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='sellerinvoice',
            name='seller_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label__in', ['accounts']), ('model__in', ['pharmacy', 'store'])), on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoices', related_query_name='seller_invoices', to='contenttypes.contenttype'),
        ),
    ]
