# Generated by Django 5.0.6 on 2024-10-15 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0034_alter_product_public_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
