# Generated by Django 5.0.6 on 2024-10-16 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0035_pharmacyoffer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyoffer',
            name='operating_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='operating_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
