# Generated by Django 5.0.6 on 2024-10-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_user_storeprofile_store'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0036_pharmacyoffer_operating_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacyinvoicestatus',
            options={'ordering': ['timestamp'], 'verbose_name_plural': 'Pharmacy invoice statuses'},
        ),
        migrations.CreateModel(
            name='PharmacyCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_cart', related_query_name='pharmacy_cart', to='accounts.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyCartDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_object_id', models.PositiveBigIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('is_offer_removed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer_content_type', models.ForeignKey(limit_choices_to=models.Q(('app_label__in', ['market']), ('model__in', ['pharmacyoffer', 'storeoffer'])), on_delete=django.db.models.deletion.PROTECT, related_name='pharmacy_cart_details', related_query_name='pharmacy_cart_details', to='contenttypes.contenttype')),
                ('pharmacy_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_cart_details', related_query_name='pharmacy_cart_details', to='market.pharmacycart')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_cart_details', related_query_name='pharmacy_cart_details', to='market.product')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyProductWishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', related_query_name='product_wishlist', to='accounts.pharmacy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_wishlist', related_query_name='product_wishlist', to='market.product')),
            ],
            options={
                'unique_together': {('product', 'pharmacy')},
            },
        ),
        migrations.DeleteModel(
            name='PharmcyProductWishList',
        ),
    ]
