# Generated by Django 5.0.6 on 2024-10-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0037_alter_pharmacyinvoicestatus_options_pharmacycart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='operating_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='pharmacyoffer',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
