# Generated by Django 5.0.6 on 2024-11-01 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0038_pharmacyinvoicedetail_operating_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='actual_discount_precentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='actual_offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
