# Generated by Django 5.0.6 on 2024-11-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0039_pharmacyinvoicedetail_actual_discount_precentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='advertising', related_query_name='advertising', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='advertising',
            name='object_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertising',
            name='redirect_type',
            field=models.CharField(choices=[('i', 'Internal'), ('e', 'External')], default='i'),
        ),
        migrations.AddField(
            model_name='company',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cc', 'Cash Car'), ('pp', 'Post Paid')], max_length=2),
        ),
    ]
