# Generated by Django 5.0.6 on 2024-11-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0040_advertising_content_type_advertising_object_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='external_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
