# Generated by Django 5.0.6 on 2024-11-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0041_advertising_external_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeoffer',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='amount_per_invoice',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storeoffer',
            name='remaining_amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
