# Generated by Django 5.0.6 on 2024-11-20 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_pharmacyprofile_area_manager_and_more'),
        ('market', '0042_storeoffer_amount_storeoffer_amount_per_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeproductcode',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product_codes', related_query_name='store_product_codes', to='market.product'),
        ),
        migrations.AlterField(
            model_name='storeproductcode',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_product_codes', related_query_name='store_product_codes', to='accounts.store'),
        ),
    ]
