# Generated by Django 5.0.6 on 2024-11-22 12:09

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_pharmacyprofile_area_manager_and_more'),
        ('market', '0043_alter_storeproductcode_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinvoice',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_offers', related_query_name='store_offers', to='market.storeproductcode'),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='discount_precentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='original_discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_offers', related_query_name='store_offers', to='market.product'),
        ),
        migrations.AlterField(
            model_name='storeoffer',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_offers', related_query_name='store_offers', to='accounts.store'),
        ),
    ]
