# Generated by Django 5.0.6 on 2024-11-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0044_alter_sellerinvoice_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinvoicestatus',
            name='icon_class',
            field=models.CharField(choices=[('a', 'fa-solid fa-thumbs-up'), ('r', 'fa-solid fa-box-archive'), ('s', 'fa-solid fa-truck'), ('d', 'fa-solid fa-check-double'), ('p', 'fa-solid fa-money-bill')], max_length=1),
        ),
    ]
