# Generated by Django 5.0.6 on 2025-04-10 00:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pharmacyprofile_last_order_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0045_alter_pharmacyinvoicestatus_icon_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedPharmacyInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_object_id', models.PositiveBigIntegerField()),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('original_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('actual_offer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_object_id', models.PositiveBigIntegerField()),
                ('min_purchase', models.FloatField()),
                ('product_expiry_date', models.DateField(null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('is_shipped', models.BooleanField()),
                ('is_delivered', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DeletedSellerInvoiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('offer_discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('discount_precentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('is_recieved', models.BooleanField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_count', models.PositiveIntegerField(default=0)),
                ('total_items_count', models.PositiveIntegerField(default=0)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_period',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='pharmacy_invoice',
        ),
        migrations.RemoveField(
            model_name='pharmacycreditlimit',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='pharmacypaymentperiod',
            name='payment_periods',
        ),
        migrations.RemoveField(
            model_name='pharmacypaymentperiod',
            name='pharmacy',
        ),
        migrations.AlterModelOptions(
            name='pharmacyinvoicestatus',
            options={'ordering': ['index', 'timestamp'], 'verbose_name_plural': 'Pharmacy invoice statuses'},
        ),
        migrations.AddField(
            model_name='pharmacycart',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacycart',
            name='total_items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacycart',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='pharmacycartdetail',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacycartdetail',
            name='offer_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='current_status',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_pharmacy_invoice', related_query_name='reverse_pharmacy_invoice', to='market.pharmacyinvoicestatus'),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='payment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacyinvoice',
            name='total_items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pharmacyinvoicedetail',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pharmacyinvoicestatus',
            name='index',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='fridge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sellerinvoice',
            name='items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerinvoice',
            name='total_items_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicestatus',
            name='icon_class',
            field=models.CharField(choices=[('a', 'fa-solid fa-thumbs-up'), ('r', 'fa-solid fa-box-archive'), ('s', 'fa-solid fa-truck'), ('d', 'fa-solid fa-check-double'), ('p', 'fa-solid fa-money-bill'), ('c', 'fa-solid fa-file-circle-check')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pharmacyinvoicestatus',
            name='style_class',
            field=models.CharField(choices=[('a', 'bg-primary'), ('r', 'bg-primary'), ('s', 'bg-primary'), ('d', 'bg-primary'), ('p', 'bg-primary'), ('c', 'bg-primary')], max_length=1),
        ),
        migrations.AlterField(
            model_name='sellerinvoicedetail',
            name='is_recieved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoicestatus',
            index=models.Index(fields=['pharmacy_invoice'], name='pis_pi_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoicestatus',
            index=models.Index(fields=['pharmacy_invoice', 'status'], name='pis_pi_status_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoicedetail',
            index=models.Index(fields=['pharmacy_invoice_detail'], name='sid_pid_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoicedetail',
            index=models.Index(fields=['seller_invoice'], name='sid_si_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoicedetail',
            index=models.Index(fields=['seller_invoice', 'product'], name='sid_si_pr_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoicedetail',
            index=models.Index(fields=['seller_invoice', 'is_accepted'], name='sid_si_accepted_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoicedetail',
            index=models.Index(fields=['seller_invoice', 'is_recieved'], name='sid_si_recieved_idx'),
        ),
        migrations.AddField(
            model_name='deletedpharmacyinvoicedetail',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletd_pharmacy_invoice_details', related_query_name='deletd_pharmacy_invoice_details', to='market.storeproductcode'),
        ),
        migrations.AddField(
            model_name='deletedpharmacyinvoicedetail',
            name='offer_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label__in', ['market']), ('model__in', ['pharmacyoffer', 'storeoffer'])), on_delete=django.db.models.deletion.PROTECT, related_name='deletd_pharmacy_invoice_details', related_query_name='deletd_pharmacy_invoice_details', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deletedpharmacyinvoicedetail',
            name='pharmacy_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletd_pharmacy_invoice_details', related_query_name='deletd_pharmacy_invoice_details', to='market.pharmacyinvoice'),
        ),
        migrations.AddField(
            model_name='deletedpharmacyinvoicedetail',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deletd_pharmacy_invoice_details', related_query_name='deletd_pharmacy_invoice_details', to='market.product'),
        ),
        migrations.AddField(
            model_name='deletedpharmacyinvoicedetail',
            name='seller_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label__in', ['accounts']), ('model__in', ['pharmacy', 'store'])), on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='deletedsellerinvoicedetail',
            name='code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_seller_invoice_details', related_query_name='deleted_seller_invoice_details', to='market.storeproductcode'),
        ),
        migrations.AddField(
            model_name='deletedsellerinvoicedetail',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='deleted_seller_invoice_details', related_query_name='deleted_seller_invoice_details', to='market.product'),
        ),
        migrations.AddField(
            model_name='deletedsellerinvoicedetail',
            name='seller_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleted_seller_invoice_details', related_query_name='deleted_seller_invoice_details', to='market.sellerinvoice'),
        ),
        migrations.AddField(
            model_name='pharmacyreturn',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_returns', related_query_name='pharmacy_returns', to='accounts.pharmacy'),
        ),
        migrations.AddField(
            model_name='pharmacyreturndetail',
            name='pharmacy_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_return_details', related_query_name='pharmacy_return_details', to='market.pharmacyinvoice'),
        ),
        migrations.AddField(
            model_name='pharmacyreturndetail',
            name='pharmacy_invoice_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_return_detail', related_query_name='pharmacy_return_detail', to='market.pharmacyinvoicedetail'),
        ),
        migrations.AddField(
            model_name='pharmacyreturndetail',
            name='pharmacy_return',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_return_details', related_query_name='pharmacy_return_details', to='market.pharmacyreturn'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='PharmacyCreditLimit',
        ),
        migrations.DeleteModel(
            name='PharmacyPaymentPeriod',
        ),
    ]
