# Generated by Django 5.0.6 on 2025-04-18 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pharmacyprofile_last_order_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0046_deletedpharmacyinvoicedetail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyinvoicestatus',
            name='status',
            field=models.CharField(choices=[('a', 'Accepted'), ('r', 'Recieved from store'), ('s', 'Shipped'), ('d', 'Delivered')], max_length=1),
        ),
        migrations.AddIndex(
            model_name='deletedpharmacyinvoicedetail',
            index=models.Index(fields=['pharmacy_invoice'], name='market_dele_pharmac_1785e6_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedpharmacyinvoicedetail',
            index=models.Index(fields=['product'], name='market_dele_product_e0cd79_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedpharmacyinvoicedetail',
            index=models.Index(fields=['offer_content_type', 'offer_object_id'], name='market_dele_offer_c_322e7b_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedsellerinvoicedetail',
            index=models.Index(fields=['seller_invoice'], name='market_dele_seller__49348c_idx'),
        ),
        migrations.AddIndex(
            model_name='deletedsellerinvoicedetail',
            index=models.Index(fields=['product'], name='market_dele_product_7f6de1_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycart',
            index=models.Index(fields=['pharmacy'], name='market_phar_pharmac_1f65ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycartdetail',
            index=models.Index(fields=['pharmacy_cart'], name='market_phar_pharmac_524d44_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycartdetail',
            index=models.Index(fields=['product'], name='market_phar_product_cc726e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycartdetail',
            index=models.Index(fields=['product', 'quantity'], name='market_phar_product_c6b701_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycartdetail',
            index=models.Index(fields=['product', 'quantity', 'offer_content_type', 'offer_object_id'], name='market_phar_product_68aba8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacycartdetail',
            index=models.Index(fields=['offer_content_type', 'offer_object_id'], name='market_phar_offer_c_a15a38_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoice',
            index=models.Index(fields=['sales'], name='market_phar_sales_i_f1ed2e_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoice',
            index=models.Index(fields=['sales', 'current_status'], name='market_phar_sales_i_c4f984_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoice',
            index=models.Index(fields=['pharmacy'], name='market_phar_pharmac_38c9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoice',
            index=models.Index(fields=['pharmacy', 'current_status'], name='market_phar_pharmac_a071cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoice',
            index=models.Index(fields=['current_status'], name='market_phar_current_5cccad_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoicedetail',
            index=models.Index(fields=['pharmacy_invoice'], name='market_phar_pharmac_8e6049_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoicedetail',
            index=models.Index(fields=['product'], name='market_phar_product_e5e9d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyinvoicedetail',
            index=models.Index(fields=['offer_content_type', 'offer_object_id'], name='market_phar_offer_c_af1181_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyoffer',
            index=models.Index(fields=['pharmacy', 'product'], name='market_phar_pharmac_3b7083_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyoffer',
            index=models.Index(fields=['product'], name='market_phar_product_366230_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyoffer',
            index=models.Index(fields=['product', 'discount_precentage'], name='market_phar_product_76c1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproductwishlist',
            index=models.Index(fields=['pharmacy'], name='market_phar_pharmac_4e7b4f_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyproductwishlist',
            index=models.Index(fields=['product'], name='market_phar_product_bf82e5_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyreturn',
            index=models.Index(fields=['pharmacy'], name='market_phar_pharmac_706270_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyreturndetail',
            index=models.Index(fields=['pharmacy_return'], name='market_phar_pharmac_e51b68_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyreturndetail',
            index=models.Index(fields=['pharmacy_invoice'], name='market_phar_pharmac_226528_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacyreturndetail',
            index=models.Index(fields=['pharmacy_invoice_detail'], name='market_phar_pharmac_7c6f32_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerinvoice',
            index=models.Index(fields=['seller_content_type', 'seller_object_id'], name='market_sell_seller__fa2fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='storeoffer',
            index=models.Index(fields=['store', 'product'], name='market_stor_store_i_118237_idx'),
        ),
        migrations.AddIndex(
            model_name='storeoffer',
            index=models.Index(fields=['product'], name='market_stor_product_76e89f_idx'),
        ),
        migrations.AddIndex(
            model_name='storeoffer',
            index=models.Index(fields=['product', 'discount_precentage'], name='market_stor_product_0cfb2c_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductcode',
            index=models.Index(fields=['product', 'store'], name='market_stor_product_726274_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductcode',
            index=models.Index(fields=['product'], name='market_stor_product_324352_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductcode',
            index=models.Index(fields=['store'], name='market_stor_store_i_b8e416_idx'),
        ),
    ]
