# Generated by Django 5.0.6 on 2025-04-20 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0047_alter_pharmacyinvoicestatus_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinvoice',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seller_invoices', related_query_name='seller_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
