# Generated by Django 5.2.6 on 2025-09-26 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_city_country_remove_city_delivery_and_more'),
        ('market', '0049_productcode_remove_advertising_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.IntegerField(blank=True, null=True)),
                ('new_code', models.IntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('deactivate', 'Deactivate'), ('reactivate', 'Reactivate')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMatchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_name', models.CharField(db_index=True, max_length=200)),
                ('confidence_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreProductCodeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/store_product_codes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('successful_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('error_log', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='storeproductcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproductcode',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeproductcode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storeproductcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='storeproductcode',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='storeproductcode',
            unique_together={('product', 'store')},
        ),
        migrations.AddIndex(
            model_name='storeproductcode',
            index=models.Index(fields=['code', 'store'], name='market_stor_code_dee534_idx'),
        ),
        migrations.AddIndex(
            model_name='storeproductcode',
            index=models.Index(fields=['is_active'], name='market_stor_is_acti_c945c1_idx'),
        ),
        migrations.AddField(
            model_name='codechangelog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='codechangelog',
            name='store_product_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.storeproductcode'),
        ),
        migrations.AddField(
            model_name='productmatchcache',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.product'),
        ),
        migrations.AddField(
            model_name='storeproductcodeupload',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.store'),
        ),
        migrations.AddIndex(
            model_name='productmatchcache',
            index=models.Index(fields=['search_name'], name='market_prod_search__4a7fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='productmatchcache',
            index=models.Index(fields=['created_at'], name='market_prod_created_5d2258_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productmatchcache',
            unique_together={('search_name', 'product')},
        ),
    ]
