# Generated by Django 5.2.6 on 2025-10-03 22:38

import django.core.validators
import django.db.models.deletion
import market.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_city_country_remove_city_delivery_and_more'),
        ('market', '0051_update_upload_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productmatchcache',
            new_name='market_prod_confide_bbaa49_idx',
            old_name='market_prod_confide_7g8h9i_idx',
        ),
        migrations.RenameIndex(
            model_name='productmatchcache',
            new_name='market_prod_last_ac_505513_idx',
            old_name='market_prod_last_ac_j1k2l3_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductcodeupload',
            new_name='market_stor_store_i_77b4a4_idx',
            old_name='market_stor_store_i_8a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductcodeupload',
            new_name='market_stor_uploade_f0567a_idx',
            old_name='market_stor_uploade_9d4e5f_idx',
        ),
        migrations.RenameIndex(
            model_name='storeproductcodeupload',
            new_name='market_stor_status_9312bb_idx',
            old_name='market_stor_status_1a2b3c_idx',
        ),
        migrations.AlterField(
            model_name='product',
            name='shape',
            field=models.CharField(choices=[('افلام', 'افلام'), ('شراب', 'شراب'), ('اسبراي', 'اسبراي'), ('استحلاب', 'استحلاب'), ('اقراص', 'اقراص'), ('اقماع', 'اقماع'), ('اكياس', 'اكياس'), ('امبولات', 'امبولات'), ('برطمان', 'برطمان'), ('بلسم', 'بلسم'), ('بودرة', 'بودرة'), ('جل', 'جل'), ('حبيبات فوار', 'حبيبات فوار'), ('زيت', 'زيت'), ('زيت شعر', 'زيت شعر'), ('سرنجة معبأه', 'سرنجة معبأه'), ('سيرم', 'سيرم'), ('شامبو', 'شامبو'), ('صابون', 'صابون'), ('غسول فم', 'غسول فم'), ('غسول مهبلي', 'غسول مهبلي'), ('غسول وجه', 'غسول وجه'), ('فوم', 'فوم'), ('فيال', 'فيال'), ('قطرة أذن', 'قطرة أذن'), ('قطرة للعين', 'قطرة للعين'), ('قلم معبأ', 'قلم معبأ'), ('قطعة', 'قطعة'), ('كبسولات', 'كبسولات'), ('كريم', 'كريم'), ('لوشن', 'لوشن'), ('محلول', 'محلول'), ('محلول استنشاق', 'محلول استنشاق'), ('مرهم', 'مرهم'), ('مرهم للعين', 'مرهم للعين'), ('مس', 'مس'), ('معلق', 'معلق'), ('نقط عين', 'نقط عين'), ('نقط فم', 'نقط فم')], max_length=20),
        ),
        migrations.AlterField(
            model_name='productmatchcache',
            name='confidence_score',
            field=models.FloatField(validators=[market.validators.ProductMatchCacheValidator.validate_confidence_score]),
        ),
        migrations.AlterField(
            model_name='productmatchcache',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_cache_entries', related_query_name='match_cache_entries', to='market.product'),
        ),
        migrations.AlterField(
            model_name='storeproductcodeupload',
            name='file',
            field=models.FileField(upload_to='uploads/store_product_codes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'xls', 'csv'], message='Only Excel (.xlsx, .xls) and CSV (.csv) files are allowed.')]),
        ),
        migrations.AlterField(
            model_name='storeproductcodeupload',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_code_uploads', related_query_name='product_code_uploads', to='accounts.store'),
        ),
    ]
