# Generated by Django 5.0.6 on 2024-07-17 06:00

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY', 'Delivery'), ('STORE', 'Store'), ('MANAGER', 'Manager'), ('SALES', 'Sales')], max_length=20)),
                ('username', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('is_ph', models.BooleanField(default=False)),
                ('is_store', models.BooleanField(default=False)),
                ('is_sales', models.BooleanField(default=False)),
                ('is_delivery', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.area')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('delivery', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_Delivery', to='accounts.delivery')),
                ('sales', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_Sales', to='accounts.sales')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ph', models.IntegerField(default=0)),
                ('num_orders', models.IntegerField(default=0)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='accounts.delivery')),
                ('area_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_manager', to='accounts.manager')),
            ],
        ),
        migrations.CreateModel(
            name='AreaProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmv', models.FloatField(default=0)),
                ('net_profit', models.FloatField(default=0)),
                ('num_ph', models.IntegerField(default=0)),
                ('num_order', models.IntegerField(default=0)),
                ('area_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='accounts.manager')),
            ],
        ),
        migrations.CreateModel(
            name='SalesProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ph', models.IntegerField(default=0)),
                ('daily_target', models.FloatField(default=1000)),
                ('monthly_target', models.FloatField(default=100000)),
                ('area_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_manager', to='accounts.manager')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='accounts.sales')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('orderbyphone', models.BooleanField(default=False)),
                ('limitstore', models.FloatField(default=100.0)),
                ('durtionstore', models.IntegerField(default=10)),
                ('limitcompany', models.FloatField(default=100.0)),
                ('durtioncompany', models.IntegerField(default=10)),
                ('block', models.BooleanField(default=False)),
                ('note', models.TextField(max_length=200)),
                ('gmv', models.FloatField(default=0)),
                ('sales_pro', models.FloatField(default=0)),
                ('num_order', models.IntegerField(default=0)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.city')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('delivery', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_delivery', to='accounts.delivery')),
                ('area_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_manager', to='accounts.manager')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_pro', to='accounts.pharmacy')),
                ('sales', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_sales', to='accounts.sales')),
            ],
        ),
        migrations.CreateModel(
            name='StoreProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=200)),
                ('precentage', models.FloatField(default=100.0)),
                ('note', models.TextField(max_length=200)),
                ('company', models.BooleanField(default=False)),
                ('gmv', models.FloatField(default=0)),
                ('key_person', models.CharField(max_length=50)),
                ('num_person', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('return_police', models.CharField(max_length=200)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('area_manager', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_manager_store', to='accounts.manager')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='accounts.store')),
            ],
        ),
    ]
