# Generated by Django 5.0.6 on 2024-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ourservices_complaints_office'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='e_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
