# Generated by Django 5.0.6 on 2024-09-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_e_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data_Entry',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='area_manager',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='durtioncompany',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='durtionstore',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='gmv',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='limitcompany',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='limitstore',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='num_order',
        ),
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='sales_pro',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='area_manager',
        ),
        migrations.RemoveField(
            model_name='storeprofile',
            name='gmv',
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='category',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='license',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='real_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='sales_store',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='update_time',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='key_person',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='precentage',
            field=models.FloatField(default=1.5),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY', 'Delivery'), ('STORE', 'Store'), ('MANAGER', 'Manager'), ('SALES', 'Sales'), ('DATA_ENTRY', 'Data_entry')], max_length=20),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='data_entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_entry', to='accounts.data_entry'),
        ),
    ]
