# Generated by Django 5.0.6 on 2024-09-23 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_data_entry_remove_pharmacyprofile_area_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pharmacyprofile',
            name='country',
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='address',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='category',
            field=models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='note',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_profile', related_query_name='pharmacy_profile', to='accounts.pharmacy'),
        ),
    ]
