# Generated by Django 5.0.6 on 2024-09-28 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_pharmacyprofile_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeprofile',
            name='data_entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_profiles', related_query_name='store_profiles', to='accounts.data_entry'),
        ),
        migrations.AlterField(
            model_name='storeprofile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_profile', related_query_name='store_profile', to='accounts.store'),
        ),
    ]
