# Generated by Django 5.0.6 on 2024-10-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_storeprofile_data_entry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY', 'Delivery'), ('STORE', 'Store'), ('MANAGER', 'Manager'), ('SALES', 'Sales'), ('DATA_ENTRY', 'Data entry')], max_length=20),
        ),
    ]
