# Generated by Django 5.0.6 on 2024-10-10 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaManager',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
        ),
        migrations.RenameField(
            model_name='pharmacyprofile',
            old_name='user',
            new_name='pharmacy',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PHARMACY', 'Pharmacy'), ('DELIVERY', 'Delivery'), ('STORE', 'Store'), ('MANAGER', 'Manager'), ('SALES', 'Sales'), ('DATA_ENTRY', 'Data entry'), ('AREA_MANAGER', 'Area manager')], max_length=20),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='area_manager',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_pharmacies', related_query_name='managed_pharmacies', to='accounts.areamanager'),
        ),
    ]
