# Generated by Django 5.0.6 on 2024-10-12 23:26

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_areamanager_rename_user_pharmacyprofile_pharmacy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("complaint", models.TextField(max_length=400)),
                ("mark_as_solved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="complaints_office",
            name="pharmacy",
        ),
        migrations.RenameModel(
            old_name="Data_Entry",
            new_name="DataEntry",
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name_plural": "Cities"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name_plural": "Countries"},
        ),
        migrations.AlterModelOptions(
            name="delivery",
            options={"verbose_name_plural": "Deliveries"},
        ),
        migrations.AlterModelOptions(
            name="pharmacy",
            options={"verbose_name_plural": "Pharmacies"},
        ),
        migrations.AlterModelOptions(
            name="sales",
            options={"verbose_name_plural": "Sales"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_delivery",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_manager",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_ph",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_sales",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_store",
        ),
        migrations.AddField(
            model_name="complaint",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="complaints",
                related_query_name="complaints",
                to="accounts.pharmacy",
            ),
        ),
        migrations.DeleteModel(
            name="Complaints_Office",
        ),
        migrations.AlterField(
            model_name="storeprofile",
            name="data_entry",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_profiles",
                related_query_name="store_profiles",
                to="accounts.dataentry",
            ),
        ),
    ]
