# Generated by Django 5.0.6 on 2024-10-14 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_complaint_remove_complaints_office_pharmacy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='data_entry',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_data_entry', related_query_name='pharmacy_data_entry', to='accounts.dataentry'),
        ),
    ]
