# Generated by Django 5.0.6 on 2024-10-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_pharmacyprofile_data_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeprofile',
            old_name='user',
            new_name='store',
        ),
    ]
