# Generated by Django 5.0.6 on 2024-11-06 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_user_storeprofile_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='area_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_pharmacies', related_query_name='managed_pharmacies', to='accounts.areamanager'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='data_entry',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_data_entry', related_query_name='pharmacy_data_entry', to='accounts.dataentry'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='delivery',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_delivery', to='accounts.delivery'),
        ),
        migrations.AlterField(
            model_name='pharmacyprofile',
            name='sales',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_sales', to='accounts.sales'),
        ),
    ]
