# Generated by Django 5.0.6 on 2025-04-10 00:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_pharmacyprofile_area_manager_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('market', '0045_alter_pharmacyinvoicestatus_icon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyprofile',
            name='last_order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pharmacyprofile',
            name='payment_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', related_query_name='pharmacies', to='market.paymentperiod'),
        ),
        migrations.CreateModel(
            name='PharmacyFinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_financial_account', related_query_name='pharmacy_financial_account', to='accounts.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyFinancialAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ib', 'Initial balance'), ('i', 'Invoice'), ('r', 'Return'), ('p', 'Payment'), ('f', 'Refund')])),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_at', models.DateTimeField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('pharmacy_financial_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_financial_account_transactions', related_query_name='pharmacy_financial_account_transactions', to='accounts.pharmacyfinancialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PharmacyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('ip', 'Instapay'), ('c', 'Cash'), ('w', 'Wallet'), ('p', 'Products')])),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', related_query_name='payments', to='accounts.pharmacy')),
            ],
        ),
    ]
