# Generated by Django 5.0.6 on 2025-04-19 16:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_pharmacyprofile_last_order_date_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerFinancialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('remaining_credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('seller', models.OneToOneField(limit_choices_to=models.Q(('role__in', ['STORE', 'PHARMACY'])), on_delete=django.db.models.deletion.CASCADE, related_name='seller_financial_account', related_query_name='seller_financial_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SellerFinancialAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ib', 'Initial balance'), ('i', 'Invoice'), ('r', 'Return'), ('p', 'Payment'), ('f', 'Refund')])),
                ('transaction_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_at', models.DateTimeField()),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('seller_finanical_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', related_query_name='transactions', to='accounts.sellerfinancialaccount')),
            ],
        ),
        migrations.CreateModel(
            name='SellerPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('ip', 'Instapay'), ('c', 'Cash'), ('w', 'Wallet'), ('p', 'Products')])),
                ('payment_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payments', related_query_name='seller_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccount',
            index=models.Index(fields=['seller'], name='accounts_se_seller__8d1567_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccounttransaction',
            index=models.Index(fields=['seller_finanical_account'], name='accounts_se_seller__cce39b_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccounttransaction',
            index=models.Index(fields=['content_type', 'object_id'], name='accounts_se_content_dde3a2_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccounttransaction',
            index=models.Index(fields=['seller_finanical_account', 'content_type', 'object_id'], name='accounts_se_seller__d65769_idx'),
        ),
    ]
