# Generated by Django 5.0.6 on 2025-04-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellerfinancialaccount_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sellerfinancialaccounttransaction',
            name='accounts_se_seller__cce39b_idx',
        ),
        migrations.RemoveIndex(
            model_name='sellerfinancialaccounttransaction',
            name='accounts_se_seller__d65769_idx',
        ),
        migrations.RenameField(
            model_name='sellerfinancialaccounttransaction',
            old_name='seller_finanical_account',
            new_name='seller_financial_account',
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccounttransaction',
            index=models.Index(fields=['seller_financial_account'], name='accounts_se_seller__6a12ba_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerfinancialaccounttransaction',
            index=models.Index(fields=['seller_financial_account', 'content_type', 'object_id'], name='accounts_se_seller__7e9028_idx'),
        ),
    ]
