# Generated by Django 5.0.6 on 2025-04-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_sellerfinancialaccounttransaction_accounts_se_seller__cce39b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerfinancialaccount',
            name='credit_limit',
        ),
        migrations.RemoveField(
            model_name='sellerfinancialaccount',
            name='remaining_credit_limit',
        ),
    ]
