# Generated by Django 5.0.6 on 2025-05-27 21:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0049_productcode_remove_advertising_content_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('available_amount', models.PositiveIntegerField()),
                ('remaining_amount', models.PositiveIntegerField()),
                ('max_amount_per_invoice', models.PositiveIntegerField(blank=True, null=True)),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('min_purchase', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_max', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to='market.product')),
                ('product_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to='market.productcode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
