# Generated by Django 5.0.6 on 2025-06-13 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0049_productcode_remove_advertising_content_type_and_more'),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to='market.productcode'),
        ),
    ]
