# Generated by Django 5.0.6 on 2025-01-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0052_rename_market_prod_confide_7g8h9i_idx_market_prod_confide_bbaa49_idx_and_more'),
        ('offers', '0004_alter_offer_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', related_query_name='offers', to='market.storeproductcode'),
        ),
    ]
