# Generated by Django 5.0.6 on 2025-05-27 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        ('market', '0049_productcode_remove_advertising_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('main', 'Main'), ('secondary', 'Secondary')])),
                ('total_items', models.PositiveIntegerField()),
                ('total_quantity', models.PositiveIntegerField()),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'indexes': [models.Index(fields=['type'], name='inventory_i_type_4fb92f_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_expiry_date', models.DateField(blank=True, null=True)),
                ('operating_number', models.CharField(blank=True, default='', max_length=255)),
                ('purchase_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_discount_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('remaining_quantity', models.PositiveIntegerField()),
                ('purchase_sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('selling_sub_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', related_query_name='items', to='inventory.inventory')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', related_query_name='inventory_items', to='market.product')),
                ('purchase_invoice_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', related_query_name='inventory_item', to='invoices.purchaseinvoiceitem')),
            ],
            options={
                'verbose_name': 'Inventory item',
                'verbose_name_plural': 'Inventory items',
            },
        ),
    ]
