from django.urls import path
from invoices import views

app_name = "invoices"

urlpatterns = [
    path(
        "purchase-invoices/",
        views.PurchaseInvoiceListView.as_view(),
        name="purchase-invoices-list-view",
    ),
    path(
        "purchase-invoices/create/",
        views.PurchaseInvoiceCreateAPIView.as_view(),
        name="purchase-invoices-create-view",
    ),
    path(
        "purchase-invoices/<int:pk>/",
        views.PurchaseInvoiceRetrieveAPIView.as_view(),
        name="purchase-invoices-object-view",
    ),
    path(
        "purchase-invoices/<int:pk>/change-state/",
        views.PurchaseInvoiceStateUpdateAPIView.as_view(),
        name="purchase-invoices-state-update-view",
    ),
    path(
        "purchase-invoice-items/",
        views.PurchaseInvoiceItemListAPIView.as_view(),
        name="purchase-invoice-items-list-view",
    ),
    path(
        "purchase-invoice-items/create/",
        views.PurchaseInvoiceItemCreateAPIView.as_view(),
        name="purchase-invoice-items-create-view",
    ),
    path(
        "purchase-invoice-items/<int:pk>/change-state/",
        views.PurchaseInvoiceItemStateUpdateAPIView.as_view(),
        name="purchase-invoice-items-state-update-view",
    ),
    path(
        "purchase-invoice-items/change-state/",
        views.PurchaseInvoiceItemBulkStateUpdateAPIView.as_view(),
        name="purchase-invoice-items-bulk-state-update-view",
    ),
    path(
        "purchase-invoice-items/<int:pk>/destroy/",
        views.PurchaseInvoiceItemDestroyAPIView.as_view(),
        name="purchase-invoice-items-delete-view",
    ),
    path(
        "purchase-return-invoices/",
        views.PurchaseReturnInvoiceListAPIView.as_view(),
        name="purchase-return-invoices-list-view",
    ),
    path(
        "purchase-return-invoices/create/",
        views.PurchaseReturnInvoiceCreateAPIView.as_view(),
        name="purchase-return-invoices-create-view",
    ),
    path(
        "purchase-return-invoices/<int:pk>/",
        views.PurchaseReturnInvoiceRetrieveAPIView.as_view(),
        name="purchase-return-invoices-object-view",
    ),
    path(
        "purchase-return-invoices/<int:pk>/change-state/",
        views.PurchaseReturnInvoiceStateUpdateAPIView.as_view(),
        name="purchase-return-invoices-state-update-view",
    ),
    path(
        "purchase-return-invoice-items/",
        views.PurchaseReturnInvoiceItemListAPIView.as_view(),
        name="purchase-return-items-list-view",
    ),
    path(
        "purchase-return-invoice-items/create/",
        views.PurchaseReturnInvoiceItemCreateAPIView.as_view(),
        name="purchase-return-items-create-view",
    ),
    path(
        "purchase-return-invoice-items/<int:pk>/change/",
        views.PurchaseReturnInvoiceItemUpdateAPIView.as_view(),
        name="purchase-return-items-update-view",
    ),
    path(
        "purchase-return-invoice-items/<int:pk>/destroy/",
        views.PurchaseReturnInvoiceItemDestroyAPIView.as_view(),
        name="purchase-return-items-delete-view",
    ),
    path(
        "sale-invoices/",
        views.SaleInvoiceListAPIView.as_view(),
        name="sale-invoices-list-view",
    ),
    path(
        "sale-invoices/create/",
        views.SaleInvoiceCreateAPIView.as_view(),
        name="sale-invoices-create-view",
    ),
    path(
        "sale-invoices/<int:pk>/",
        views.SaleInvoiceRetrieveAPIView.as_view(),
        name="sale-invoices-object-view",
    ),
    path(
        "sale-invoices/<int:pk>/download/",
        views.SaleInvoiceDownloadAPIView.as_view(),
        name="sale-invoices-download-view",
    ),
    path(
        "sale-invoices/<int:pk>/change-state/",
        views.SaleInvoiceStateUpdateAPIView.as_view(),
        name="sale-invoices-state-update-view",
    ),
    path(
        "sale-invoice-items/",
        views.SaleInvoiceItemListAPIView.as_view(),
        name="sale-invoice-items-list-view",
    ),
    path(
        "sale-invoice-items/create/",
        views.SaleInvoiceItemCreateAPIView.as_view(),
        name="sale-invoice-items-create-view",
    ),
    path(
        "sale-invoice-items/<int:pk>/change/",
        views.SaleInvoiceItemUpdateAPIView.as_view(),
        name="sale-invoice-items-update-view",
    ),
    path(
        "sale-invoice-items/<int:pk>/change-state/",
        views.SaleInvoiceItemStateUpdateAPIView.as_view(),
        name="sale-invoice-items-state-update-view",
    ),
    path(
        "sale-invoice-items/change-state/",
        views.SaleInvoiceItemBulkStateUpdateAPIView.as_view(),
        name="sale-invoice-items-bulk-state-update-view",
    ),
    path(
        "sale-invoice-items/<int:pk>/destroy/",
        views.SaleInvoiceItemDestroyAPIView.as_view(),
        name="sale-invoice-items-delete-view",
    ),
    path(
        "sale-return-invoices/",
        views.SaleReturnInvoiceListAPIView.as_view(),
        name="sale-return-invoices-list-view",
    ),
    path(
        "sale-return-invoices/create/",
        views.SaleReturnInvoiceCreateAPIView.as_view(),
        name="sale-return-invoices-create-view",
    ),
    path(
        "sale-return-invoices/<int:pk>/",
        views.SaleReturnInvoiceRetrieveAPIView.as_view(),
        name="sale-return-invoices-object-view",
    ),
    path(
        "sale-return-invoices/<int:pk>/change-state/",
        views.SaleReturnInvoiceStateUpdateAPIView.as_view(),
        name="sale-return-invoices-state-update-view",
    ),
    path(
        "sale-return-invoice-items/",
        views.SaleReturnInvoiceItemListAPIView.as_view(),
        name="sale-return-items-list-view",
    ),
    path(
        "sale-return-invoice-items/create/",
        views.SaleReturnInvoiceItemCreateAPIView.as_view(),
        name="sale-return-items-create-view",
    ),
    path(
        "sale-return-invoice-items/<int:pk>/change/",
        views.SaleReturnInvoiceItemUpdateAPIView.as_view(),
        name="sale-return-items-update-view",
    ),
    path(
        "sale-return-invoice-items/<int:pk>/destroy/",
        views.SaleReturnInvoiceItemDestroyAPIView.as_view(),
        name="sale-return-items-delete-view",
    ),
]
