# Generated by Django 5.2.6 on 2025-10-18 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='FCM Token الفريد للجهاز', unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('android', 'Android'), ('ios', 'iOS')], default='web', help_text='نوع الجهاز (web, android, ios)', max_length=10)),
                ('device_name', models.CharField(blank=True, help_text='اسم الجهاز (اختياري)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='هل التوكن نشط؟')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used', models.DateTimeField(blank=True, help_text='آخر مرة تم استخدام التوكن لإرسال إشعار', null=True)),
                ('user', models.ForeignKey(help_text='المستخدم صاحب التوكن', on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', related_query_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FCM Token',
                'verbose_name_plural': 'FCM Tokens',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', 'is_active'], name='notificatio_user_id_fcm_idx'),
                    models.Index(fields=['token'], name='notificatio_token_idx'),
                    models.Index(fields=['device_type'], name='notificatio_device_idx'),
                ],
            },
        ),
    ]

